version: "3.9"
services:
  api:
    build: ../
    container_name: aria_api
    env_file: ../.env
    environment:
      MONGO_URI: ${MONGO_URI}
      QDRANT_URL: ${QDRANT_URL}
      REDIS_URL: ${REDIS_URL}
      S3_ENDPOINT: ${S3_ENDPOINT}
      S3_ACCESS_KEY: ${S3_ACCESS_KEY}
      S3_SECRET_KEY: ${S3_SECRET_KEY}
      S3_BUCKET: ${S3_BUCKET}
      S3_REGION: ${S3_REGION}
    depends_on:
      - mongo
      - qdrant
      - redis
      - minio
    ports:
      - "8088:8088"
    command: uvicorn api.main:app --host 0.0.0.0 --port 8088 --proxy-headers --forwarded-allow-ips="*"

  mongo:
    image: mongo:7
    container_name: aria_mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${ARIA_MONGO_ROOT_USER:-aria}
      MONGO_INITDB_ROOT_PASSWORD: ${ARIA_MONGO_ROOT_PASSWORD}
    volumes:
      - ./data/mongo:/data/db
    ports:
      - "27017:27017"

  qdrant:
    image: qdrant/qdrant:latest
    container_name: aria_qdrant
    volumes:
      - ./data/qdrant:/qdrant/storage
    ports:
      - "6333:6333"

  redis:
    image: redis:7
    container_name: aria_redis
    ports:
      - "6379:6379"

  minio:
    image: minio/minio
    container_name: aria_minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${ARIA_MINIO_ROOT_USER:-aria}
      MINIO_ROOT_PASSWORD: ${ARIA_MINIO_ROOT_PASSWORD}
    volumes:
      - ./data/minio:/data
    ports:
      - "9000:9000"
      - "9001:9001"
